version: '3.6'
services:

  rabbitmq:
    image: "rabbitmq:3.7-alpine"
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  worker:
    build:
      context: ./
      dockerfile: prepare/Dockerfile
    restart: always
    env_file:
      - secret-vars.env
    environment:
      RABBIT_HOST: rabbitmq
      VIDEO_QUEUE_NAME: localhost-video-queue
      PYTHONUNBUFFERED: 1
    volumes:
      - type: bind
        source: ./data
        target: /data
